#nom du module
name: Config override
#description du module
description: config module for d8 developper training.
#type de code
type: module
#version de drupal
core: 8.x
#version
version: 8.x-1.0
package: Training
#dependencie
dependencies:
  - views
  - field